### ISSUE TITLE
StreamProcessor.startBlocking() is misleading

### ISSUE THREAD

**Issue by GJL** [zalando-incubator/nakadi-java#107]
It is not clear to me when `startBlocking()` should be preferred over `start()`. 

`startBlocking()` immediately returns although the library is consuming events. This is because event emissions and subscriptions are performed on the `monoComputeScheduler` defined in  the `nakadi.StreamProcessor` class. From the name I expected the calling thread to block.

**Comment by dehora** [comment]
@GJL yep, `startBlocking` was added to make it a bit easier to develop and experiment with the client; `start()` is the intended way to use the client for a running system. I expect `startBlocking` will get nuked prior to a 1.0.0. In the meantime, probably best to mark `startBlocking` deprecated and a latch to it. Going to leave this open for now, and tag it on the 1.0.0 milestone.

**Comment by dehora** [comment]
fixed in #108
