### ISSUE TITLE
Using certificate path with "classpath:" doesn't work, if you want to load certificates from a JAR

### ISSUE THREAD

**Issue by dcherepovsky** [zalando-incubator/nakadi-java#126]
Not sure if it's a bug of just expected behavior. If it is, IMO should be documented.

Maybe it would be useful [to use Zip File System Provider](https://docs.oracle.com/javase/8/docs/technotes/guides/io/fsp/zipfilesystemprovider.html) in case if user wants to load certificates from JAR.

**Comment by dehora** [comment]
#159 allows a single cert to be loaded from the classpath. I think that's about as far as the feature should go (it's ultimately a workaround for systems using self-signed certs but not having those certs available on developer machines).
