### ISSUE TITLE
Failing to reconnect to subscription after disconnect

### ISSUE THREAD

**Issue by MikhailGolubtsov** [zalando-incubator/nakadi-java#165]
After an error in commiting offset the client could not reconnect and felt in a loop trying to do this forever.

> May 10 20:18:54 ip-172-31-159-69 docker/4f1edd2aed0e[812]: 2017-05-10 20:18:54 [nakadi-java-io-0] INFO NakadiClient - disposing connection on thread nakadi-java-io-0 2104337645 HttpResponse{response=Response{protocol=http/1.1, code=200, message=OK, url=/subscriptions/2309d9c0-261b-43d6-9a40-b7d391bf1575/events?batch_limit=5&batch_flush_timeout=3&max_uncommitted_events=1}}
May 10 20:18:54 ip-172-31-159-69 docker/4f1edd2aed0e[812]: 2017-05-10 20:18:54 [nakadi-java-io-0] DEBUG d.z.w.l.CustomerItemCancellationRequestedListener - Completed reading events of event type fulfillment.shipment-order-item-cancellation-requested
22:18:54.894 cancellation-service-live /var/log/application.log May 10 20:18:54 ip-172-31-159-69 docker/4f1edd2aed0e[812]: 2017-05-10 20:18:54 [nakadi-java-io-0] INFO  NakadiClient - stream repeater invoked 0 restarts=1  
22:18:54.894 cancellation-service-live /var/log/application.log May 10 20:18:54 ip-172-31-159-69 docker/4f1edd2aed0e[812]: 2017-05-10 20:18:54 [nakadi-java-io-0] INFO  NakadiClient - stream repeater will delay before restarting, delay=3 seconds, restarts=1  
22:18:57.691 cancellation-service-live /var/log/application.log May 10 20:18:57 ip-172-31-159-69 docker/4f1edd2aed0e[812]: 2017-05-10 20:18:57 [nakadi-java-io-0] INFO  NakadiClient - stream_connection details mode=subscriptionStream resolved_event_name=fulfillment.shipment-order-item-cancellation-requested url=/subscriptions/2309d9c0-261b-43d6-9a40-b7d391bf1575/events?batch_limit=5&batch_flush_timeout=3&max_uncommitted_events=1 scope=nakadi.event_stream.read  
22:18:57.691 cancellation-service-live /var/log/application.log May 10 20:18:57 ip-172-31-159-69 docker/4f1edd2aed0e[812]: 2017-05-10 20:18:57 [nakadi-java-io-0] INFO  NakadiClient - stream_connection opening 562090725 HttpResponse{response=Response{protocol=http/1.1, code=200, message=OK, url=/subscriptions/2309d9c0-261b-43d6-9a40-b7d391bf1575/events?batch_limit=5&batch_flush_timeout=3&max_uncommitted_events=1}}  
22:19:57.892 cancellation-service-live /var/log/application.log May 10 20:19:57 ip-172-31-159-69 docker/4f1edd2aed0e[812]: 2017-05-10 20:19:57 [nakadi-java-io-0] INFO  NakadiClient - disposing connection on thread nakadi-java-io-0 562090725 HttpResponse{response=Response{protocol=http/1.1, code=200, message=OK, url=/subscriptions/2309d9c0-261b-43d6-9a40-b7d391bf1575/events?batch_limit=5&batch_flush_timeout=3&max_uncommitted_events=1}}  
22:19:57.892 cancellation-service-live /var/log/application.log May 10 20:19:57 ip-172-31-159-69 docker/4f1edd2aed0e[812]: 2017-05-10 20:19:57 [nakadi-java-io-0] DEBUG d.z.w.l.CustomerItemCancellationRequestedListener - Completed reading events of event type fulfillment.shipment-order-item-cancellation-requested  

Initial error:

> 22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: 2017-05-10 20:18:15 [nakadi-java-compute-0] ERROR NakadiClient - stream_processor_err_compute Thread[nakadi-java-compute-0,5,main], timeout;  (400)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: nakadi.NetworkException: timeout;  (400)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.OkHttpResource.executeRequest(OkHttpResource.java:256)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.OkHttpResource.requestInner(OkHttpResource.java:193)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.OkHttpResource.requestThrowingInner(OkHttpResource.java:188)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.OkHttpResource.lambda$requestThrowing$5(OkHttpResource.java:147)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.io.reactivex.internal.operators.observable.ObservableDefer.subscribeActual(ObservableDefer.java:32)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.io.reactivex.Observable.subscribe(Observable.java:10842)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.io.reactivex.Observable.blockingFirst(Observable.java:4727)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.OkHttpResource.requestThrowing(OkHttpResource.java:149)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.SubscriptionResourceReal.checkpoint(SubscriptionResourceReal.java:165)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.SubscriptionResourceReal.checkpoint(SubscriptionResourceReal.java:127)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.SubscriptionOffsetCheckpointer.checkpoint(SubscriptionOffsetCheckpointer.java:94)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.SubscriptionOffsetCheckpointer.checkpoint(SubscriptionOffsetCheckpointer.java:47)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.SubscriptionOffsetCheckpointer.checkpoint(SubscriptionOffsetCheckpointer.java:32)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.SubscriptionOffsetObserver.checkpoint(SubscriptionOffsetObserver.java:28)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.SubscriptionOffsetObserver.onNext(SubscriptionOffsetObserver.java:21)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at de.zalando.whip.listener.CustomerItemCancellationRequestedListener.onNext(CustomerItemCancellationRequestedListener.java:83)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.StreamBatchRecordSubscriber.onNext(StreamBatchRecordSubscriber.java:41)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.StreamBatchRecordSubscriber.onNext(StreamBatchRecordSubscriber.java:7)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:400)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:260)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:225)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at java.lang.Thread.run(Thread.java:745)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: Caused by: java.net.SocketTimeoutException: timeout  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.okio.Okio$4.newTimeoutException(Okio.java:227)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.okio.AsyncTimeout.exit(AsyncTimeout.java:284)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.okio.AsyncTimeout$2.read(AsyncTimeout.java:240)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.okio.RealBufferedSource.indexOf(RealBufferedSource.java:344)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:216)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)  
22:18:18.674 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)  
22:18:18.675 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)  
22:18:18.675 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)  
22:18:18.675 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)  
22:18:18.675 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)  
22:18:18.675 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)  
22:18:18.675 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.okhttp3.RealCall.execute(RealCall.java:69)  
22:18:18.675 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.OkHttpResource.okHttpCall(OkHttpResource.java:285)  
22:18:18.675 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.OkHttpResource.executeRequest(OkHttpResource.java:254)  
22:18:18.675 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011... 24 common frames omitted  
22:18:18.675 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: Caused by: java.net.SocketException: Socket closed  
22:18:18.675 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at java.net.SocketInputStream.read(SocketInputStream.java:203)  
22:18:18.675 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at java.net.SocketInputStream.read(SocketInputStream.java:141)  
22:18:18.675 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)  
22:18:18.675 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at sun.security.ssl.InputRecord.read(InputRecord.java:503)  
22:18:18.675 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)  
22:18:18.675 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)  
22:18:18.675 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)  
22:18:18.675 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.okio.Okio$2.read(Okio.java:138)  
22:18:18.675 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011at nakadi.shadow.okio.AsyncTimeout$2.read(AsyncTimeout.java:236)  
22:18:18.675 cancellation-service-live /var/log/application.log May 10 20:18:15 ip-172-31-159-69 docker/4f1edd2aed0e[812]: #011... 45 common frames omitted

**Comment by dehora** [comment]
> After an error in commiting offset the client could not reconnect and felt in a loop trying to do this forever.

If the observer throws an exception, the consumer will generally stop, as it can't know that to proceed and ignore the crash is ok. Generally observers should catch the exceptions they want to recover from.

Checkpointing related failures are so common, that there are two workarounds for general network problems and invalid (stale) session ids. Network handling was added in [0.8.1](https://github.com/zalando-incubator/nakadi-java/blob/master/CHANGES.md#081) and invalid handling was added in [0.7.11](https://github.com/zalando-incubator/nakadi-java/blob/master/CHANGES.md#0711). The error in the trace is a network problem (typically a slow nakadi server), so that would mean using 0.8.1 or higher unless you want to catch and ignore this in the observer code by wrapping StreamOffsetObserver.onNext in a catch.

There's a test here that shows how to configure them: [StreamProcessorTest.java#L393-L402](https://github.com/zalando-incubator/nakadi-java/blob/25020db6dd706c9184aa31f1fe0e89c139700d8a/nakadi-java-client/src/test/java/nakadi/StreamProcessorTest.java#L393-L402)
