### ISSUE TITLE
consumer_group param doesn't restrict the subscriptions returned

### ISSUE THREAD

**Issue by HungUnicorn** [zalando-incubator/nakadi-java#187]
We would like to delete subscriptions given the consumer group.  But the code below doesn't recognize `consumer_group` parameter, but only the `owning_application`. It also doesn't return all the subscriptions we have given `owning_application`.
```
 resource.list(new QueryParams()
                .param("consumer_group", consumerGroup)
                .param("owning_application", application))
                .items()
```

**Comment by dehora** [comment]
> But the code below doesn't recognize consumer_group parameter, but only the owning_application.

I can't replicate this. For this dummy example:

```java
    final SubscriptionResource subscriptions = client.resources().subscriptions();
    final List<Subscription> items = subscriptions.list(new QueryParams()
        .param("consumer_group", "cg")
        .param("owning_application", "app"))
        .items();
```
I see this url being sent:

```
<-- 200 OK https://nakadi-example.org/subscriptions?consumer_group=cg&owning_application=app (681ms)
```

Regardless the api definition in master doesn't have a documented `consumer_group` parameter. ([link](https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L886-L921)).

> It also doesn't return all the subscriptions we have given owning_application.

You'll want to check if the server you're working with is returning a paginated list. This from your example 

```
resource.list(new QueryParams()
                .param("consumer_group", consumerGroup)
                .param("owning_application", application))
                .items()
```

only returns the first page sent back from the server via `.items()`. If you need to paginate, you'll want to use the iterable option available via the `SubscriptionCollection` return by `resource.list(QueryParams)` or directly iterate through the next pages using `nextPage()` and `hasNextLink()`. You should check if the server is returning pagination links and not just one single page that happens to not contain all the expected subs.

Can you provide some more details on you're expecting to have sent and returned maybe with `.enableHttpLogging()` set on the client.

**Comment by HungUnicorn** [comment]
I got 
`Exception in thread "main" java.lang.IllegalArgumentException: unexpected url: /subscriptions?owning_application=flux-flink&offset=20&limit=20`

the code is as
`SubscriptionCollection resourceList = client.resources().subscriptions().list(new QueryParams()
                .param("owning_application", application)
        while(resourceList.hasNextLink()) {
            resourceList.nextPage();
            for (Subscription item : resourceList.items()) {
                if (item.consumerGroup().toLowerCase().contains(consumerGroup.toLowerCase())
                        && item.owningApplication()
                        .equalsIgnoreCase(application)) {
                    subscriptionList.add(item.id());
                }
            }
        }`

The limit works, but we prefer to iterate pages. Any suggestion?
