### ISSUE TITLE
Unauthorized (401) response not processed correctly

### ISSUE THREAD

**Issue by olayinkasf** [zalando-incubator/nakadi-java#188]
The `Problem` created for the response below doesn't contain enough information to understand

````
{"error":"unauthorized","error_description":"Full authentication is required to access this resource"}

Problem{type=about:blank, title='null', status=0, detail='null', instance=null, data=null}
````

Perhaps the line 
````
    if (problem.status() == 0 && response.statusCode() == 400) 
````
should accommodate for 401 as well

**Comment by dehora** [comment]
> Unauthorized (401) response not processed correctly
> The Problem created for the response below doesn't contain enough information to understand

This is related to Nakadi's https://github.com/zalando/nakadi/issues/645 - the server returns the wrong structure. Do you have an example request of a bad response structure returned with a 401?

**Comment by dehora** [comment]
There's a workaround in 0.8.6. It's be great if you could go upstream and comment on or like zalando/nakadi#645. Having to patch around what should be a simple server fix in api clients is unfortunate.

**Comment by olayinkasf** [comment]
Actually, it suffices for me to not provide an access token and I get a 401 response.

**Comment by meghana-khr** [comment]
Did you solve this problem??
